# Generated by Django 6.0 on 2025-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(max_length=50),
        ),
    ]
